#!/bin/sh
set -eu

: "${RENEWED_LINEAGE:?RENEWED_LINEAGE is required}"
deploy_root=${VPN_DEPLOY_ROOT:-/opt/vpn-node}

install -m 0400 "$RENEWED_LINEAGE/fullchain.pem" \
    "$deploy_root/secrets/hysteria-tls.crt"
install -m 0400 "$RENEWED_LINEAGE/privkey.pem" \
    "$deploy_root/secrets/hysteria-tls.key"

cd "$deploy_root"
docker compose up -d --no-deps --force-recreate hysteria
